name: fluencybank
description: FluencyBank Application
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

authors:
  - Albert Li <superdev999@gmail.com>

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  toast: ^0.1.5
  email_validator: '^1.0.0'
  datetime_picker_formfield: ^0.4.0
  intl: ^0.15.8
  http: ^0.12.0+2
  modal_progress_hud: ^0.1.3
  geolocator: ^5.1.1
  flutter_masked_text:
  percent_indicator: ^2.1.1
  share:
  flutter_cupertino_date_picker: ^1.0.12
  flutter_datetime_picker: ^1.2.5
  keyboard_actions:
  contacts_service: 
  permission_handler: 
  shared_preferences:
  line_awesome_icons:
  grouped_buttons:
  timeline_list:
  qr_flutter:
  path_provider: 
  barcode_scan:
  


dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/flags/

  fonts:
   - family: Gilroy
     fonts:
       - asset: assets/fonts/Gilroy-ExtraBold.ttf
         weight: 900
       - asset: assets/fonts/Gilroy-Bold.ttf
         weight: 800
       - asset: assets/fonts/Gilroy-SemiBold.ttf
         weight: 700
       - asset: assets/fonts/Gilroy-Medium.ttf
         weight: 400
       - asset: assets/fonts/Gilroy-Regular.ttf
         weight: 300
       - asset: assets/fonts/Gilroy-UltraLight.ttf
         weight: 200
       - asset: assets/fonts/Gilroy-Thin.ttf
         weight: 100
